### PR TITLE
Update config.schema.json

### PR DESCRIPTION
**Pull request by apexad**
Addition to #5
This will be needed too. Does this make sense for this to be in advanced settings?

### CODE REVIEW

**Comment by iAnatoly** [comment]
Sure, why not. It is not very advanced by nature, but I do not think average user would need to adjust this.

**Comment by apexad** [comment]
Looks like this and #5 were pushed to npmjs.com as version 0.0.8 now.  Can you please push the commit to master that bumps the version in the package.json so everything is in sync?

**Comment by iAnatoly** [comment]
My bad, I was sure I pushed it. Will do tonight.

**Comment by iAnatoly** [comment]
Done. Apparently I did push --tags, but this only pushes tags (even though the tag is applied to a commit that has not been pushed yet). Sorry about that.

**Pull request merged**
